# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'  # Adjust based on your Java version
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      mvn clean package
    displayName: 'Build Spring Boot App with Maven'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target'
      Contents: '*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy JAR to Artifact Staging'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'spring-app-artifact'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'
