spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/saraha'
    username: postgres
    password: bilel

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  profiles:
    active:

  main:
    banner-mode: off
server:
  port: 8080
  servlet:
    context-path: /saraha-api
    # Server configuration
